version: '3'

services:
  cassandra:
    image: cassandra:4.0.3
    container_name: cassandra
    ports:
      - '7000:7000'
      - '9042:9042'
    volumes:
      - ./data/cassandra:/bitnami
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
