version: '3.1'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.28
    ports:
      - "3306:3306"
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    volumes:
      - ./data/mysql/data:/var/lib/mysql
      - ./data/mysql/config:/etc/mysql/conf.d
#      - ../db:/docker-entrypoint-initdb.d