version: "2"
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    env_file:
      - env/nacos-standlone-mysql.env
    volumes:
      - ./standalone-logs/:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9555:9555"
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:8.0.28
    ports:
      - "3306:3306"
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    volumes:
      - ./data/mysql/data:/var/lib/mysql
      - ./data/mysql/config:/etc/mysql/conf.d
      - ./db:/docker-entrypoint-initdb.d
