version: "3"

services:
  redis:
    image: 'docker.io/redis'
    restart: always
    hostname: redis
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --requirepass bin --appendonly yes
    volumes:
      - ./redis/data:/data
